.github/workflows/build.yml

- <https://github.com/VOICEVOX/voicevox_core/issues/54#issuecomment-1003274192>
上のコメントの内容を反映させるPRです。
- 公式Release: <https://github.com/microsoft/onnxruntime/releases/tag/v1.9.0>
公式ReleaseではLinux用のビルドはtgz形式で配布されているので、Releaseにアップロードされる形式をzipからtgzに変更します。
Windows用のビルドが追加されることがあれば、分岐してzipにする形がいいかなと思っています。
また、公式Releaseでは圧縮ファイル内の一番上に、圧縮ファイル名と同名のディレクトリがありますが、このリポジトリのReleaseにはありません。コアのビルドは公式Releaseの構造を前提にしているので、構造を合わせます。
- <https://github.com/aoirint/onnxruntime-builder/releases/tag/1.9.1-aoirint-3>
- ref <https://github.com/VOICEVOX/voicevox_core/pull/56>
- ref <https://github.com/VOICEVOX/voicevox_core/issues/54>
改行コードがCRLFになっているのと、空行が消えているので調整したいです。
`Rearchive artifact`と`Upload to Release`は、Release以外のときにJobが実行されることを想定していないですが、`workflow_dispatch`があるので条件分岐を入れておいた方がよさそうだなと思いました（動いてそうなのでそのままでもいいかもですが …

自動ビルド: リリースをtgz形式に変更・ルートディレクトリを追加

---

.github/workflows/build.yml

現時点ではtgzという拡張子が付いたただのtarアーカイブになっているので正しい形式に修正します。
(解凍しようとした時の7zipのログの一部)
```
Extracting archive: onnxruntime-linux-armhf-cpu-v1.9.1.tgz
WARNING:
onnxruntime-linux-armhf-cpu-v1.9.1.tgz
Can not open the file as [gzip] archive
The file is open as [tar] archive
```
- ref #2

リリースの配布形式を修正

---

.github/workflows/build.yml

mainブランチにpushされたとき、タグが作成されたとき、リリースが作成されたときの3回リリースへのアップロードがされるようになっていました。
後者の2回は同じリリースにアップロードしようとして、上書きに失敗し、CIのステータスが失敗になります。
このPRでは、リリースへのアップロードをリリースが作成されたときだけにして、CIが失敗しないようにします。
たしか上書きすることもできますが、リリースされた成果物が書き換わるのは避けた方がいいと思いました。
---
mainブランチにpushされたときにリリースにアップロードが成功するのは意外な動作でしたが、mainというタグでリリースを自動作成するようなので、整備するとlatestビルドとして使えるかもしれないと思いました。

自動ビルド: リリースに複数回アップロードが走らないように修正

---

.github/workflows/build.yml

ONNX Runtime v1.10.0のバイナリをビルドするようにします。
releaseブランチを作ってもいいかもです。
- <https://github.com/aoirint/onnxruntime-builder/releases/tag/1.10.0-aoirint-1>
ref <https://github.com/VOICEVOX/voicevox_core/issues/60>

自動ビルド: ONNXRuntime v1.10.0に更新

---

.github/workflows/build.yml

arm64向けOnnx Runtimeの自動ビルドを追加を追加します。
Raspberry Pi OSでビルドしたVOICEVOX COREが正常に動作することを確認しています。

arm64向けOnnx Runtimeの自動ビルドを追加

---

.github/workflows/build.yml

Fixes #9.
よくわかりませんが、これで通るようです。
<https://github.com/qryxip/onnxruntime-builder/actions/runs/4517776385>

Symlinkの張り方を更新

---

.github/workflows/build.yml

#13 のhttps://github.com/VOICEVOX/onnxruntime-builder/pull/13#issuecomment-1501160118 で触れたように、このリポジトリでビルドされるonnxruntimeの成果物の命名ルールは、microsoft/onnxruntimeで配布されている成果物の命名ルールと異なります。
このPRでは、成果物の命名ルールをmicrosoft/onnxruntimeで配布される成果物の命名ルールに合わせます。
#13 
https://github.com/VOICEVOX/onnxruntime-rs/pull/19

バージョンプレフィックスを削除

---

.github/workflows/build.yml

バージョン指定を可能にしました。
- https://github.com/VOICEVOX/onnxruntime-builder/issues/15
- https://github.com/VOICEVOX/onnxruntime-rs/pull/19

バージョン指定を可能にする

---

.github/workflows/build.yml

iOS向けのXCFrameworkをビルドするGitHub Actionsを追加します。
このPRでは次の要素を追加しました。
1. 各ターゲット向けdylibのUpload(`build-onnxruntime` job上)
2. シミュレータ向けdylibのFat binary化(`build_xcframework` job上)
3. XCFrameworkの作成(`build_xcframework` job上)
close #18 
https://github.com/VOICEVOX/voicevox_core/issues/477
https://github.com/VOICEVOX/voicevox_core/pull/485

iOS向けXCFrameworkを追加する

---

.github/workflows/build.yml

xcframeworkはmacOSでも存在し得るらしいです。
ここでアップロードされているxcframeworkはios専用なので、そのことがわかるように`ios-`prefixを追加します。
- https://github.com/VOICEVOX/voicevox_core/pull/485#discussion_r1199254761
ちなみに本家のonnxruntimeの命名はこんな感じです。
https://github.com/microsoft/onnxruntime/releases/tag/v1.14.1

xcframeworkの命名規則を変える

---

.github/workflows/build.yml

shell: bashを不要にできるオプションがあったので指定してみました。
とりあえずubuntu以外でのOSで実行していたworkflowにのみ付けています。
https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun

Github Actionsでshell: bashを毎回書かなくても良いようにする

---

.github/workflows/build.yml

CMakeのバージョンも上げます。
- https://github.com/VOICEVOX/onnxruntime-builder/pull/11

onnxruntimeのバージョンを1.15.1に上げる

---

.github/workflows/build.yml

コンパイルエラーの解消
#715
https://github.com/VOICEVOX/voicevox_core/issues/715#issuecomment-1872865577
必要があればマージください

build.ymlでpython 3.10のインストール

---

.github/workflows/build.yml

現時点で最新であるv1.16.3で、VOICEVOX COREに必要なすべてのターゲットをビルドします。
- VOICEVOX/voicevox_core#718
- VOICEVOX/voicevox_project#24

残りのターゲットをビルドする

---

.github/workflows/build.yml

macOSのarm64ビルドが正しくできるよう修正
現行のビルドスクリプトでは、`onnxruntime-osx-arm64`  が x86_64になってしまう問題を修正します
[Release 1.16.3](https://github.com/VOICEVOX/onnxruntime-builder/releases/tag/1.16.3) から `onnxruntime-osx-arm64-1.16.3.tgz` をDLして、下記コマンドを実行すると確認できます。
```
>  file onnxruntime-osx-arm64-1.16.3/lib/libonnxruntime.dylib
onnxruntime-osx-x86_64-1.16.3/lib/libonnxruntime.1.16.3.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```
本PRをマージして、再ビルドすると下記のようになるはずです
```
onnxruntime-osx-arm64-1.16.3/lib/libonnxruntime.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

macOSのarm64ビルドが正しくできるよう修正

---

.github/workflows/build.yml

iOSではない、macOS用のものを`macos-12`ではなく`macos-11`でビルドするようにします。

macOS用のものを`macos-11`でビルドする

---

.github/workflows/build.yml

ビルド時にwarningsが出ないよう、下記actionsを更新
- actions/cache
- actions/checkout
- actions/download-artifacts
- actions/upload-artifacts
実行結果に影響がない軽微な修正のため、落ち着いたタイミングで反映してみてください

ビルド時にwarningsが出ないよう修正

---

.github/workflows/build.yml

ビルドに使うCUDAをv12.2にします。
<https://github.com/VOICEVOX/voicevox_additional_libraries/pull/3>に合わせました。
- #36

CUDAをv12.2に

---

.github/workflows/build.yml

cuda-toolkitをv0.2.15に上げ、<https://github.com/Jimver/cuda-toolkit/issues/315>に対するワークアラウンドを削除します。

cuda-toolkitをv0.2.15に上げる

---

.github/workflows/build.yml
1_17_3_android_arm64_build.patch

ONNX Runtimeをv1.17.3に

---

.github/workflows/build.yml

VOICEVOX/voicevox_core#810 のための変更の一つです。
(VOICEVOX/voicevox_core#810 から依存されているのは、このPRそのものではなく #44 です)
リリースするONNX Runtimeについて機械可読な`<table>`を置き、CORE側のダウンローダーから認識できるようにします。
ref VOICEVOX/voicevox_core#810

add: リリースノートに機械可読な`<table>`を置く

---

.github/workflows/build.yml

VOICEVOX/voicevox_additional_libraries#4 をやったときのように、LinuxのCUDA版に限りjlumbroso/free-disk-spaceを導入します。
最近になってついに容量が足りなくなり始めたためです。
<https://github.com/qryxip/onnxruntime-builder/actions/runs/10226248892/job/28296262761>

chore: LinuxのCUDA版にjlumbroso/free-disk-spaceを導入

---

.github/workflows/build.yml

#43 の実装の上に、リリースとして`onnxruntime-win-x64-gpu-without-cuda`を追加します。
出力例: <https://github.com/qryxip/onnxruntime-builder/releases/tag/1.17.3>
ref #43
ref VOICEVOX/voicevox_core#810

add: `onnxruntime-win-x64-gpu-cuda`を追加

---

.github/workflows/build.yml

経緯: <https://github.com/VOICEVOX/onnxruntime-builder/issues/46#issuecomment-2290765448>

remove: CUDAとDirectMLの両方を有効化したビルドは提供しない

---

.github/workflows/build.yml

`build_opts`の整理をします。
1. 全ビルドに共通し、かつ共通し続けるであろうオプションをまとめる
2. YAMLの`|-`を使った複数行の記述方式にし、`#`でコメントも加えられるようにする
- 実際にいくつかコメントを加える
3. 統一感が出るようにオプションの順番も整える
モチベーションとしては、このリポジトリの秘伝のタレ化を少しでも防ぐためです。

chore: `build_opts`を整理する

---

.github/workflows/build.yml

Bashスクリプト中の`${{ env.環境変数 }}`を`$環境変数`にするリファクタを行います。
理由としては、`${{ env.環境変数 }}`で書いたとしても特に静的解析が効くわけではなく、むしろShellCheckの邪魔になるからです。actionlint下では`$環境変数`の方がよいと思いました。
<https://github.com/qryxip/onnxruntime-builder/actions/runs/10630507299/job/29469582836>

chore: `${{ env.環境変数 }}` → `$環境変数`

---

.github/workflows/build.yml
.github/workflows/shellcheck.yml
codesign.bash

add: コード署名

---

.github/workflows/build.yml

以下のファイルをリリースに含めないようにします。
- [Privacy.md](https://github.com/microsoft/onnxruntime/blob/v1.19.0/docs/Privacy.md) (我々のは"private build"であるため)
- include/
ちなみにpykeio/ortでのONNX Runtimeのダウンロード物はこんな感じになっています。内部利用専用であるためreadmeもありません。
```console
❯ tar --list -f ./ortrs-msort_dylib_cu12-v1.19.0-x86_64-pc-windows-msvc.tgz
onnxruntime/lib/onnxruntime.dll
onnxruntime/lib/onnxruntime.lib
onnxruntime/lib/onnxruntime_providers_cuda.dll
onnxruntime/lib/onnxruntime_providers_shared.dll
onnxruntime/lib/onnxruntime_providers_shared.lib
onnxruntime/lib/onnxruntime_providers_tensorrt.dll
```

remove: 不要なファイルをリリースに入れないようにする

---

.github/workflows/build.yml

voicevox_onnxruntimeをビルドできるようにします。
`inputs.target = "onnxruntime" | "voicevox_onnxruntime"`でビルド対象を選び、`"voicevox_onnxruntime"`の場合次の`secrets`を用いたビルドとなります。
- `${{ secrets.PRODUCTION_GITHUB_TOKEN }}`: 現行COREのと同じ役割
- `${{ secrets.PRODUCTION_REPOSITORY_URL }}`: 現行COREのと同じ役割
- `${{ secrets.PRODUCTION_DISCORD_WEBHOOK }}`: 失敗時にビルドログを送信（個人で動作確認済）
対象タグは`v{バージョン}-voicevox`で固定です。
ref VOICEVOX/voicevox_project#24

add: voicevox_onnxruntimeをビルドできるようにする

---

.github/workflows/build.yml

この辺の区分けがよくわかっていませんが、今`voicevox_onnxruntime`のビルド自体に`production`を使っているのでこうしようかと。

feat!: 署名ではなく`voicevox_onnxruntime`に`production`を使う

---

.github/workflows/build.yml

追記: <https://github.com/VOICEVOX/onnxruntime-builder/pull/61#issuecomment-2564582707>
Refs: https://github.com/VOICEVOX/voicevox_core/issues/888#issuecomment-2564133514

fix: iOS以外`CMAKE_SYSTEM_PROCESSOR`を指定

---

.github/workflows/build.yml

voicevox_onnxruntime用のスクリプトをvoicevox_onnxruntime側に移したので、それを使うようにする。
Refs: VOICEVOX/voicevox_project#24

chore: voicevox_onnxruntimeのprepare.bashを使う

---

.github/workflows/build.yml

Refs: VOICEVOX/voicevox_project#24

chore: `voicevox_onnxruntime`では`cache-build-result`をスキップ

---

.github/workflows/build.yml

現在、ワークフローの最後のリリースノートの書き込みのときにリリースがprereleaseになるようになっている。
<https://github.com/VOICEVOX/onnxruntime-builder/blob/00edd0759d44cc3fe3a2460e0b898c09da1ef5bf/.github/workflows/build.yml#L787-L792>
しかし、最初にリリースが作られる段階ではprereleaseではないようなので、最初からprereleaseになるようにする。

fix: Releaseの作成時点で`prerelease: true`

---

1_17_3_strip.patch

macOS: `-s, --strip-all`は存在しないので、代わりに`-Sx` (`--strip-debug --discard-all`)で`strip`する。
ARM版Linux: 現段階では諦める。
#73 のビルドを確認しないままマージしたことによって壊れてしまったので、それに対する修正です。

fix: fix up #73: `strip(1)`が使えないケースは諦める

---

.github/workflows/build.yml

third-party-notices.htmlにORTのlicenseとnoticesを含めるようにしたため。
またORTのREADME.mdも入れないようにする。

feat!: ORT自体のreadme, license, noticesをファイルとして含めない

---

1_17_3_windows.patch

microsoft/onnxruntime#23911 の問題をONNX Runtime v1.17で解決するために`#include <chrono>`を挟む。
Suggested-by: @yamachu
(ありがとうございます！)

fix: v1.17のWindowsビルドを直す

---

.github/workflows/build.yml

See-also: https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/

feat!: Ubuntu 20.04のサポートを切る
